Repository daostack/alchemy, pull requests merged in 2020-07, with the labels that each got.

#1912 Use infura env var
  src/settings.ts
Labels: 2.0

#1917 Data decoding is now in arc.js
  package-lock.json
  package.json
  src/components/Proposal/ProposalSummary/ProposalSummaryPluginManager.tsx
  src/lib/pluginUtils.ts
  src/lib/plugins_initilization_params.json
Labels: 2.0

#1919 Updated subgraph version from v8.6 to v8.7
  docker-compose.yml
  package-lock.json
  package.json
  src/subgraph_endpoints.json
Labels: 2.0

#1945 fix access to DAOs on ganache
  CHANGELOG.md
  src/components/Dao/DaoLandingPage.tsx
Labels: 1.0

#1944 fix description label bugs
  src/components/Proposal/Create/SchemeForms/CreateKnownGenericSchemeProposal.tsx
  src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx
Labels: 1.0

#1937 UI/UX improvments
  src/assets/images/Icon/search.svg
  src/assets/images/loading.gif
  src/assets/images/spinnyBusyIcon.gif
  src/components/Dao/DaoLandingPage.scss
  src/components/Dao/PluginCard.scss
  src/components/Dao/UnknownPluginCard.scss
  src/components/Daos/DaoCard.tsx
  src/components/Daos/Daos.scss
  src/components/Plugin/PluginInfo.scss
  src/components/Proposal/Create/CreateProposal.scss
  src/components/Proposal/ProposalCard.scss
  src/components/Proposal/ProposalDetails.scss
  src/components/Shared/FollowButton.scss
  src/components/Shared/Loading.scss
  src/components/Shared/Loading.tsx
  src/layouts/App.scss
  src/layouts/SidebarMenu.tsx
Labels: 2.0

#1951 Simple UX changes
  src/assets/styles/global-variables.scss
  src/components/Dao/DaoPluginsPage.scss
  src/components/Daos/Daos.scss
  src/components/Daos/DaosPage.tsx
  src/components/Plugin/Plugin.scss
Labels: 2.0

#1958 kovan: fixed no Custom Contract To Call field at plugin manager
  src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx
Labels: 2.0

#1962 eth.js polling is now 60 seconds
  src/arc.ts
  src/layouts/SidebarMenu.tsx
  src/lib/util.ts
Labels: 2.0

#1946 eliminate forceUpdate in Header
  src/layouts/Header.tsx
Labels: 2.0

#1976 fix computation of GEN available for staking - 1.0
  src/lib/util.ts
Labels: 1.0, Bug

#1949 upgrade lint tools
  .eslintrc
  package-lock.json
  package.json
  src/App.tsx
  src/actions/profilesActions.ts
  src/actions/web3Actions.ts
  src/arc.ts
  src/components/Buidlhub/BuidlhubClient.ts
  src/components/Dao/DaoHistoryPage.tsx
  src/components/Dao/ProposalPluginCard.tsx
  src/components/Daos/DaosPage.tsx
  src/components/Plugin/PluginContainer.tsx
  src/components/Plugin/PluginOpenBountyPage.tsx
  src/components/Plugin/PluginProposalsPage.tsx
  src/lib/util.ts
  src/settings.ts
Labels: 2.0

#1998 Fix Analytics failure ; Fix redeem issue
  package-lock.json
  package.json
  src/actions/arcActions.ts
  src/components/Proposal/ActionButton.tsx
Labels: 2.0

#1947 upgrade 3Box
  package-lock.json
  package.json
  src/assets/styles/global-variables.scss
  src/components/Account/Account.scss
  src/components/Buidlhub/Registration.scss
  src/components/Dao/Dao.scss
  src/components/Dao/DaoLandingPage.scss
  src/components/Dao/DaoPluginsPage.scss
  src/components/Dao/DaoPluginsPage.tsx
  src/components/Dao/PluginCard.scss
  src/components/Daos/Daos.scss
  src/components/Feed/Feed.scss
  src/components/Plugin/ContributionRewardExtRewarders/Competition/Competitions.scss
  src/components/Plugin/Plugin.scss
  src/components/Plugin/PluginProposals.scss
  src/components/Proposal/ActionButton.scss
  src/components/Proposal/Create/CreateProposal.scss
  src/components/Proposal/ProposalDetails.scss
  src/components/Proposal/Staking/StakeButtons.scss
  src/components/Redemptions/RedemptionsMenu.scss
  src/components/Redemptions/RedemptionsPage.scss
  src/components/Shared/SocialShareModal.scss
Labels: 2.0

#1994 Update daocreator package 1.0
  package-lock.json
  package.json
  src/components/DaoCreator/index.tsx
Labels: 1.0

#2000 remove obsolete work-around
  src/components/Proposal/ProposalDetailsPage.tsx
Labels: 2.0

#2007 Predictions UI fix
  src/components/Proposal/ProposalDetailsPage.tsx
Labels: 2.0, UI

#2002 handle all arc.js datetime types
  src/components/Plugin/ContributionRewardExtRewarders/Competition/utils.ts
  src/components/Proposal/Voting/VoteButtons.tsx
  src/lib/proposalHelpers.ts
  src/lib/proposalUtils.ts
  src/lib/util.ts
Labels: 2.0

#2005 fix computation of networkId
  src/arc.ts
  src/lib/util.ts
Labels: 2.0

#1997 fix Competion link visibility on proposal details
  src/components/Proposal/ProposalDetailsPage.tsx
Labels: 2.0

#2014 Infrastructure for language localization with i18next and removing static text redundancy
  package-lock.json
  package.json
  src/assets/locales/en/translation.json
  src/assets/styles/global.scss
  src/components/Dao/DaoContainer.tsx
  src/components/Dao/DaoLandingPage.tsx
  src/components/Dao/DaoPluginsPage.tsx
  src/components/Daos/DaosPage.tsx
  src/components/Plugin/ContributionRewardExtRewarders/Competition/CreateProposal.tsx
  src/components/Plugin/ContributionRewardExtRewarders/Competition/CreateSubmission.tsx
  src/components/Plugin/PluginContainer.tsx
  src/components/Plugin/PluginProposalsPage.tsx
  src/components/Proposal/Create/PluginForms/CreateContributionRewardProposal.tsx
  src/components/Proposal/Create/PluginForms/CreateKnownGenericPluginProposal.tsx
  src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
  src/components/Proposal/Create/PluginForms/CreatePluginRegistrarProposal.tsx
  src/components/Proposal/Create/PluginForms/CreateUnknownGenericPluginProposal.tsx
  src/components/Shared/HelpButton.tsx
  src/i18n.js
  src/index.tsx
  src/layouts/Header.tsx
  src/layouts/SidebarMenu.tsx
Labels: 2.0, Feature

#1996 Release 0.10.13
  CHANGELOG.md
  data/tokens.json
  package-lock.json
  package.json
  src/arc.ts
  src/components/Dao/DaoSchemesPage.tsx
  src/components/Proposal/Create/SchemeForms/CreateContributionRewardProposal.tsx
  src/lib/schemeUtils.ts
  src/lib/util.ts
Labels: 1.0

#2023 fix text location in daos search input on Safari
  src/components/Daos/Daos.scss
Labels: UI

#2020 bump daocreator version - 2
  package-lock.json
  package.json
Labels: 2.0

#2028 Fix hover border location ; Using global variable for border color
  src/assets/styles/global-variables.scss
  src/components/Dao/PluginCard.scss
Labels: 2.0, UI

#2017 Eliminate lint warnings
  .travis.yml
  src/actions/arcActions.ts
  src/actions/profilesActions.ts
  src/actions/uiActions.ts
  src/actions/web3Actions.ts
  src/arc.ts
  src/components/Buidlhub/BuidlhubClient.ts
  src/components/Buidlhub/Registration.tsx
  src/components/Dao/DaoDiscussionPage.tsx
  src/components/Dao/DaoLandingPage.tsx
  src/components/Dao/SimplePluginCard.tsx
  src/components/Dao/UnknownPluginCard.tsx
  src/components/DaoCreator/index.tsx
  src/components/Daos/DaoCard.tsx
  src/components/Errors/Error404.tsx
  src/components/Errors/ErrorUncaught.tsx
  src/components/Feed/FeedItem.tsx
  src/components/Plugin/ContributionRewardExtRewarders/Competition/CreateProposal.tsx
  src/components/Plugin/ContributionRewardExtRewarders/Competition/CreateSubmission.tsx
  src/components/Plugin/ContributionRewardExtRewarders/Competition/Details.tsx
  src/components/Plugin/ContributionRewardExtRewarders/Competition/utils.ts
  src/components/Plugin/PluginContainer.tsx
  src/components/Plugin/PluginOpenBountyPage.tsx
  src/components/Plugin/ReputationFromToken.tsx
  src/components/Proposal/Create/PluginForms/CreateContributionRewardProposal.tsx
  src/components/Proposal/Create/PluginForms/CreateKnownGenericPluginProposal.tsx
  src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
  src/components/Proposal/Create/PluginForms/CreatePluginRegistrarProposal.tsx
  src/components/Proposal/Create/PluginForms/CreateUnknownGenericPluginProposal.tsx
  src/components/Proposal/Create/PluginForms/Validators.ts
  src/components/Proposal/ProposalDetailsPage.tsx
  src/components/Proposal/ProposalSummary/ProposalSummary.tsx
  src/components/Proposal/RedemptionsTip.tsx
  src/components/Shared/Countdown.tsx
  src/components/Shared/Loading.tsx
  src/components/Shared/ModalPopup.tsx
  src/components/Shared/ProposalCountdown.tsx
  src/components/Shared/ProposalDescription.tsx
  src/components/Shared/withSubscription.tsx
  src/genericPluginRegistry/index.ts
  src/lib/analytics.ts
  src/lib/pluginUtils.ts
  src/lib/sortService.ts
  src/reducers/profilesReducer.ts
  src/reducers/uiReducer.ts
  src/reducers/web3Reducer.ts
  test/integration/utils.ts
Labels: 2.0
