Repository daostack/alchemy, pull requests merged in 2020-08, with the labels that each got.

#2034 Edit plugin redirects to replace tab
  src/components/Plugin/PluginContainer.tsx
Labels: 2.0

#2036 expand genericscheme docs
  src/genericSchemeRegistry/README.md
Labels: 1.0

#2037 expose app version - 1.0
  .github/ISSUE_TEMPLATE/bug_report.md
  src/layouts/Header.tsx
  typings/build.d.ts
  webpack.base.config.js
Labels: 1.0

#2031 Simple UX/UI improvments
  src/assets/images/loading.gif
  src/assets/styles/global-variables.scss
  src/components/Dao/PluginCard.scss
  src/components/Dao/ProposalPluginCard.tsx
  src/components/Daos/Daos.scss
  src/components/Proposal/Create/CreateProposal.scss
  src/layouts/App.scss
Labels: 2.0, UI

#2026 show raw calldata (1.0)
  src/components/Proposal/ProposalSummary/ProposalSummaryCO2ken.tsx
  src/components/Proposal/ProposalSummary/ProposalSummaryDutchX.tsx
  src/components/Proposal/ProposalSummary/ProposalSummaryKnownGenericScheme.tsx
  src/components/Proposal/ProposalSummary/ProposalSummaryStandardBounties.tsx
Labels: 1.0

#2042 Support for DAOs sorting
  src/assets/images/Icon/sort-order-arrow.svg
  src/assets/locales/en/translation.json
  src/components/Daos/DaoCard.tsx
  src/components/Daos/Daos.scss
  src/components/Daos/DaosPage.tsx
Labels: 2.0, Feature

#1979 conserve modal form entries
  package-lock.json
  package.json
  src/assets/images/Icon/eraser.svg
  src/assets/locales/en/translation.json
  src/assets/styles/global-variables.scss
  src/components/Account/Account.scss
  src/components/Dao/DaoPluginsPage.scss
  src/components/Plugin/ContributionRewardExtRewarders/Competition/Competitions.scss
  src/components/Plugin/ContributionRewardExtRewarders/Competition/CreateProposal.tsx
  src/components/Plugin/ContributionRewardExtRewarders/Competition/CreateSubmission.tsx
  src/components/Plugin/Plugin.scss
  src/components/Plugin/PluginProposals.scss
  src/components/Proposal/ActionButton.scss
  src/components/Proposal/Create/CreateProposal.scss
  src/components/Proposal/Create/PluginForms/CreateContributionRewardProposal.tsx
  src/components/Proposal/Create/PluginForms/CreateKnownGenericPluginProposal.tsx
  src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
  src/components/Proposal/Create/PluginForms/CreatePluginRegistrarProposal.tsx
  src/components/Proposal/Create/PluginForms/CreateUnknownGenericPluginProposal.tsx
  src/components/Proposal/Create/PluginForms/ResetFormButton.scss
  src/components/Proposal/Create/PluginForms/ResetFormButton.tsx
  src/components/Proposal/Create/PluginForms/TagsSelector.tsx
  src/components/Shared/FormModalService.tsx
  src/components/Shared/UserSearchField.tsx
  src/lib/proposalUtils.ts
  src/lib/util.ts
  test/integration/plugin-manager.ts
  test/integration/proposal-genericPluginRegistryLookup.ts
  test/integration/proposal-pluginregistrar.ts
  test/integration/utils.ts
  test/integration/wdio.conf.js
Labels: 2.0

#2045 New proposal button is now disabled when a plugin is not activated yet
  src/assets/locales/en/translation.json
  src/components/Plugin/Plugin.scss
  src/components/Plugin/PluginContainer.tsx
Labels: 2.0, UI

#2052 add genericscheme callData raw data to the proposal details view
  src/assets/locales/en/translation.json
  src/components/Proposal/ProposalSummary/ProposalSummaryCO2ken.tsx
  src/components/Proposal/ProposalSummary/ProposalSummaryDutchX.tsx
  src/components/Proposal/ProposalSummary/ProposalSummaryKnownGenericPlugin.tsx
  src/components/Proposal/ProposalSummary/ProposalSummaryNFTManager.tsx
  src/components/Proposal/ProposalSummary/ProposalSummaryStandardBounties.tsx
Labels: 2.0

#2068 Fix dxd token display
  CHANGELOG.md
  data/tokens.json
  package-lock.json
  package.json
Labels: 1.0, Bug

#2072 Updated arc.js, test env and subgraph
  docker-compose.yml
  docs/Alchemy_2_0_Benefits.md
  package-lock.json
  package.json
  src/actions/arcActions.ts
  src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
  src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx
  src/subgraph_endpoints.json
Labels: 2.0

#2071 Plugin manager modal UI improvments
  src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
Labels: 2.0, UI

#2070 Fix UI where votes screwed up
  src/components/Proposal/Voting/VoteBreakdown.scss
Labels: 2.0, UI

#2069 Better UI for DAO history page
  src/components/Proposal/ProposalHistoryRow.scss
Labels: 2.0, UI

#2018 refactor and fix issues relating 3box operations
  package-lock.json
  src/actions/profilesActions.ts
  src/actions/web3Actions.ts
  src/assets/locales/en/translation.json
  src/components/Account/AccountProfilePage.tsx
  src/reducers/profilesReducer.ts
  src/reducers/web3Reducer.ts
Labels: 2.0

#2077 Fix issue when a proposal card is not always clickable
  src/components/Proposal/ProposalCard.scss
  src/components/Proposal/ProposalCard.tsx
Labels: 2.0

#2075 revert subgraph endpoint domain
  CHANGELOG.md
  package-lock.json
  package.json
  src/subgraph_endpoints.json
Labels: 1.0

#2078 revert subgraph endpoint domain
  src/subgraph_endpoints.json
Labels: 2.0

#2085 Support DAOs sort by total holdings
  src/assets/locales/en/translation.json
  src/components/Daos/DaoCard.tsx
  src/components/Daos/Daos.scss
  src/components/Daos/DaosPage.tsx
  src/lib/util.ts
Labels: 2.0, Feature

#2064 display proposal event history
  CHANGELOG.md
  src/components/Proposal/ProposalDetails.scss
  src/components/Proposal/ProposalDetailsPage.tsx
  src/lib/util.ts
Labels: 1.0

#2089 Minor adjustments due to changes in DAOs balances service
  src/components/Daos/DaosPage.tsx
Labels: 2.0
