Repository daostack/alchemy, pull requests merged in 2020-11, with the labels that each got.

#2230 Avoid crashing Alchemy when there is no network or The Graph servers are overloaded - 2.0
  src/arc.ts
Labels: 2.0, Bug

#2232 Avoid crashing Alchemy when there is no network or The Graph servers are overloaded - 1.0
  src/arc.ts
Labels: 1.0, Bug

#2239 Fix modal service nesting ; remove unnecessary console log
  src/arc.ts
  src/lib/proposalUtils.ts
Labels: 2.0, Bug

#2197 Support generic multi-call scheme - 1.0
  docker-compose.yml
  package-lock.json
  package.json
  src/components/Proposal/Create/CreateProposal.scss
  src/components/Proposal/Create/CreateProposalPage.tsx
  src/components/Proposal/Create/SchemeForms/ABIService.ts
  src/components/Proposal/Create/SchemeForms/CreateGenericMultiCallProposal.tsx
  src/components/Proposal/Create/SchemeForms/Validators.ts
  src/components/Proposal/ProposalSummary/ProposalSummary.scss
  src/components/Proposal/ProposalSummary/ProposalSummary.tsx
  src/components/Proposal/ProposalSummary/ProposalSummaryMultiCallGenericScheme.tsx
  src/lib/schemeUtils.ts
  src/lib/util.ts
  test/integration/proposal.ts
Labels: 1.0, Feature

#2254 Support method arrays params in generic multi-call
  src/components/Proposal/Create/SchemeForms/ABIService.ts
  src/components/Proposal/Create/SchemeForms/CreateGenericMultiCallProposal.tsx
  src/components/Proposal/Create/SchemeForms/Validators.ts
  src/components/Proposal/ProposalSummary/ProposalSummaryMultiCallGenericScheme.tsx
  src/components/Scheme/SchemeInfoPage.tsx
  webpack.dev.config.js
  webpack.docker.config.js
  webpack.prod.config.js
Labels: Bug, Feature

#2258 feat: add link xGEN --> GEN
  src/layouts/SidebarMenu.tsx
Labels: Feature

#2257 Ignore network and GraphQL errors
  src/arc.ts
  src/components/Shared/withSubscription.tsx
Labels: Bug

#2265 Fix wrong share link
  src/components/Proposal/ProposalDetailsPage.tsx
Labels: Bug

#2266 fix: fix vulnerabilities
  .travis.yml
  package-lock.json
  package.json
  src/components/Dao/DaoSchemesPage.scss
Labels: Bug, Enhancement, security

#2281 Fix 3box following issue
  package-lock.json
  package.json
Labels: Bug

#2288 Show GP params in competition scheme
  src/components/Scheme/SchemeInfoPage.tsx
Labels: Bug
