Repository daostack/alchemy, pull requests merged in 2020-12, with the labels that each got.

#2302 update subgraph v41_1
  src/subgraph_endpoints.json
Labels: Maintenance

#2299 chore: improve CI performance. Travis and gitlab - both
  .gitlab-ci.example.yml
  .gitlab-ci.yml
  .travis.yml
  .travis/branch.yml
  .travis/pr.yml
  package.json
Labels: Enhancement

#2301 Brand new Proposals Page
  docs/fetchingandsubscribingdata.md
  src/assets/styles/global-variables.scss
  src/components/Dao/DaoContainer.tsx
  src/components/Dao/DaoHistoryPage.scss
  src/components/Dao/DaoHistoryPage.tsx
  src/components/Dao/DaoLandingPage.scss
  src/components/Dao/DaoLandingPage.tsx
  src/components/Dao/DaoProposalsPage.scss
  src/components/Dao/DaoProposalsPage.tsx
  src/components/Dao/DaoSchemesPage.tsx
  src/components/Notification/Notification.scss
  src/components/Proposal/ProposalHistoryRow.scss
  src/components/Proposal/ProposalHistoryRow.tsx
  src/components/Proposal/ProposalRow.scss
  src/components/Proposal/ProposalRow.tsx
  src/components/Proposal/Staking/StakeButtons.tsx
  src/components/Scheme/ContributionRewardExtRewarders/rewardersProps.ts
  src/components/Scheme/SchemeProposalsPage.tsx
  src/components/Shared/withSubscription.tsx
  src/layouts/SidebarMenu.tsx
  src/lib/proposalHelpers.ts
  src/lib/schemeUtils.ts
  src/pages.ts
  test/integration/history.e2e.ts
Labels: Feature, UI, UX

#2318 Use arc.js 0.2.78 ; add execute calls button to multicall proposals
  package-lock.json
  package.json
  src/actions/arcActions.ts
  src/components/Proposal/ActionButton.scss
  src/components/Proposal/ActionButton.tsx
Labels: Bug

#2296 New proposal window with select
  .travis/branch.yml
  .travis/pr.yml
  src/assets/styles/global-variables.scss
  src/components/Dao/DaoContainer.tsx
  src/components/Dao/DaoProposalsPage.tsx
  src/components/Proposal/Create/CreateProposal.scss
  src/components/Proposal/Create/CreateProposalPage.tsx
  src/components/Proposal/Create/SchemeForms/CreateContributionRewardProposal.tsx
  src/components/Proposal/Create/SchemeForms/CreateGenericMultiCallProposal.tsx
  src/components/Proposal/Create/SchemeForms/CreateKnownGenericSchemeProposal.tsx
  src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx
  src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx
  src/components/Proposal/Create/SelectProposal/SelectProposal.scss
  src/components/Proposal/Create/SelectProposal/SelectProposal.tsx
  src/components/Proposal/Create/SelectProposal/SelectProposalLabel/SelectProposalLabel.scss
  src/components/Proposal/Create/SelectProposal/SelectProposalLabel/SelectProposalLabel.tsx
  src/components/Proposal/Create/SelectProposal/SelectProposalLabel/index.ts
  src/components/Proposal/Create/SelectProposal/index.ts
  src/components/Proposal/Create/index.ts
  src/components/Proposal/ProposalCard.tsx
  src/components/Proposal/ProposalData.tsx
  src/components/Proposal/ProposalDetailsPage.tsx
  src/components/Scheme/ContributionRewardExtRewarders/rewardersProps.ts
  src/components/Scheme/SchemeContainer.tsx
  src/components/Shared/withSubscription.tsx
  src/lib/schemeUtils.ts
Labels: Feature, UI, UX

#2313 Verify parameters hash
  src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx
  test/integration/proposal-schemeregistrar.e2e.ts
  test/integration/utils.ts
Labels: Improvement

#2330 Fix banner overlaps
  src/layouts/SidebarMenu.scss
  test/integration/proposal-genericSchemeDutchx.e2e.ts
Labels: UI

#2333 Fix execute call button condition
  src/components/Proposal/ActionButton.tsx
Labels: Bug

#2334 Update plugins icon instead of history icon
  src/assets/images/Icon/menu/history.svg
  src/assets/images/Icon/menu/plugins.svg
  src/layouts/SidebarMenu.tsx
Labels: UI

#2325 Update changelog for 1.0.4
  CHANGELOG.md
Labels: changelog

#2331 fix: fix storybook
  .storybook/webpack.config.js
Labels: Bug

#2336 feat: hide add proposal button if empty schemes array
  src/components/Dao/DaoContainer.tsx
  src/components/Dao/DaoProposalsPage.tsx
  src/components/Dao/DaoSchemesPage.tsx
  src/components/Proposal/Create/SelectProposal/SelectProposal.tsx
  src/lib/schemeUtils.ts
Labels: Enhancement

#2338 add box shadow to schemes select
  src/components/Proposal/Create/SelectProposal/SelectProposal.scss
Labels: UI

#2341 fix: show all known schemes
  src/lib/schemeUtils.ts
Labels: Bug

#2342 fix: rerender popup content when changing proposal type
  src/components/Proposal/Create/CreateProposalPage.tsx
  src/components/Proposal/Create/SchemeForms/CreateGenericMultiCallProposal.tsx
Labels: Enhancement

#2343 Some release 1.0.4 issues
  src/components/Account/Account.scss
  src/components/Dao/Dao.scss
  src/components/Dao/DaoContainer.tsx
  src/components/Dao/DaoProposalsPage.scss
  src/components/Dao/DaoProposalsPage.tsx
  src/components/Daos/Daos.scss
  src/components/Daos/DaosPage.tsx
  src/components/Proposal/ActionButton.scss
  src/components/Proposal/Create/CreateProposalPage.tsx
  src/components/Redemptions/RedemptionsMenu.tsx
  src/components/Redemptions/RedemptionsPage.tsx
  src/components/Shared/ModalPopup.scss
  src/components/Shared/ModalPopup.tsx
  src/components/Shared/PreTransactionModal.tsx
  src/layouts/App.scss
  src/layouts/AppContainer.tsx
  src/layouts/Header.tsx
  src/layouts/SidebarMenu.scss
  src/lib/proposalHelpers.ts
Labels: Bug, Improvement, UI, UX

#2357 Fix proposal long content with html code tag
  src/components/Proposal/ProposalDetails.scss
Labels: UI, UX

#2358 Show proposal countdown only if it's not 0
  src/components/Proposal/ProposalRow.tsx
Labels: UI, UX

#2361 fix: proposal info tab
  src/components/Dao/DaoContainer.tsx
  src/components/Proposal/Create/CreateProposalPage.tsx
Labels: Bug

#2360 Updated subgraph, arc.js and migration ; updated condition to pre-boosted proposals
  docker-compose.yml
  package-lock.json
  package.json
  src/components/Proposal/Create/SelectProposal/SelectProposalLabel/SelectProposalLabel.tsx
  src/components/Proposal/ProposalRow.scss
  src/components/Proposal/ProposalRow.tsx
  src/components/Shared/ProposalCountdown.tsx
  src/genericSchemeRegistry/schemes/ENSRegistry.json
  src/genericSchemeRegistry/schemes/RegistryLookup.json
  src/lib/proposalHelpers.ts
  src/subgraph_endpoints.json
  test/integration/proposal-competition.e2e.ts
  test/integration/proposal-schemeregistrar.e2e.ts
Labels: Bug, Improvement

#2352 Update changelog to 1.0.4 release
  CHANGELOG.md
Labels: changelog

#2365 Get correct network
  src/arc.ts
  src/components/Proposal/Create/CreateProposalPage.tsx
  src/components/Proposal/Create/SchemeForms/ABIService.ts
  src/components/Proposal/Create/SchemeForms/CreateGenericMultiCallProposal.tsx
  src/components/Proposal/ProposalSummary/ProposalSummary.tsx
  src/components/Proposal/ProposalSummary/ProposalSummaryMultiCallGenericScheme.tsx
  src/components/Proposal/RedemptionsString.tsx
  src/components/Proposal/Voting/VoteButtons.tsx
  src/components/Redemptions/RedemptionsPage.tsx
  src/components/Scheme/ReputationFromToken.tsx
  src/genericSchemeRegistry/index.ts
  src/layouts/SidebarMenu.tsx
  src/lib/schemeUtils.ts
Labels: Bug

#2368 verify schemeToAdd(plugin) params and not the plugin manager itself
  src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx
  test/integration/proposal-genericSchemeEnsPublicResolver.e2e.ts
  test/integration/proposal-schemeregistrar.e2e.ts
Labels: Bug

#2370 Better code for schemeName function
  src/lib/schemeUtils.ts
Labels: Bug

#2371 Show loader on breadcrumb change
  src/components/Dao/DaoContainer.tsx
Labels: UI, UX

#2372 Remove xdai link on sidebar
  src/layouts/SidebarMenu.tsx
Labels: UI

#2373 chore: remove gitlab. It doesnt work better, then travis
  .gitlab-ci.yml
Labels: Tests

#2377 Some UI/UX improvements
  src/assets/images/spinnyBusyIcon.gif
  src/components/Daos/DaoCard.tsx
  src/components/Daos/Daos.scss
  src/components/Proposal/ProposalCard.scss
  src/components/Proposal/ProposalDetails.scss
  src/components/Shared/Loading.scss
Labels: UI, UX

#2376 scheme can be undefined due to unknown issue
  src/components/Proposal/ProposalDetailsPage.tsx
Labels: Blocked, Bug

#2378 Update arc.js
  package-lock.json
  package.json
Labels: Bug
