Repository daostack/alchemy, pull requests merged in 2020-06, with the labels that each got.

#1787 improve scheme info layout
  src/components/Scheme/SchemeInfo.scss
  src/components/Scheme/SchemeInfoPage.tsx
Labels: Mobile

#1826 don't split GenericScheme name
  src/lib/schemeUtils.ts
Labels: Bug, UI

#1823 Added validation of GP parameters
  src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx
  src/components/Proposal/Create/PluginForms/Validators.ts
  src/components/Proposal/ProposalSummary/ProposalSummaryPluginManager.tsx
Labels: 2.0

#1835 Activation time is now converted from Date object to posix time
  src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
  src/lib/util.ts
Labels: 2.0

#1842 Fix UI issue in staking modal
  src/components/Shared/PreTransactionModal.scss
Labels: 2.0, UI

#1849 Added validation to Custom Contract To Call field
  src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx
Labels: 2.0

#1854 Automate params in test/integration/utils
  test/integration/utils.ts
Labels: 2.0

#1865 Decode pluginToRegisterData and extract the real plugin name
  src/components/Proposal/ProposalSummary/ProposalSummaryPluginManager.tsx
  src/lib/pluginUtils.ts
Labels: 2.0

#1864 Added default future date for activation time
  .travis.yml
  src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
Labels: 2.0

#1866 Added plugin manager autotest
  src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
  test/integration/plugin-manager.ts
  test/integration/utils.ts
Labels: 2.0, Tests

#1884 Show voting params to proposals that were created
  src/components/Proposal/ProposalSummary/ProposalSummaryPluginManager.tsx
  src/lib/pluginUtils.ts
  src/lib/plugins_initilization_params.json
Labels: 2.0

#1895 Disable closing modal when clicking on the modal backdrop (outside)
  src/components/Shared/ModalPopup.scss
  src/layouts/App.scss
  src/layouts/AppContainer.tsx
Labels: 2.0

#1903 Support Torus (issue #1829)
  src/assets/styles/global.scss
  src/settings.ts
Labels: 2.0

#1886 Update tests to use the robust function to hide cookies window
  test/integration/plugin-manager.ts
  test/integration/utils.ts
Labels: 2.0

#1821 Add the GEMS token to the new proposal token list, for i4
  data/tokens.json
Labels: Feature
