Repository daostack/alchemy, pull requests merged in 2020-10, with the labels that each got.

#2157 Added fieldsets in Plugin Manager ---> Plugin Registrar
  src/assets/locales/en/translation.json
  src/components/Proposal/Create/CreateProposal.scss
  src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx
Labels: 2.0, UI

#2161 Show all registered daos when SHOW_ALL_DAOS is set to false
  src/components/Daos/DaosPage.tsx
Labels: 2.0, Bug

#2163 Update node.js version
  .travis.yml
  package.json
Labels: Maintenance

#2167 Update condition to support Add and Replace plugin
  src/components/Plugin/PluginInfoPage.tsx
  src/components/Proposal/ProposalSummary/ProposalSummary.scss
  src/components/Proposal/ProposalSummary/ProposalSummaryPluginManager.tsx
Labels: Bug

#2171 add PINC token
  data/tokens.json
Labels: 2.0

#2173 Fix competition tab crash ; Fix compitition plugin ugly name
  src/components/Plugin/ContributionRewardExtRewarders/Competition/List.tsx
  src/lib/pluginUtils.ts
Labels: 2.0, Bug

#2179 Merge dev-2 to master-2
  .travis.yml
  data/tokens.json
  package.json
  src/components/Plugin/ContributionRewardExtRewarders/Competition/List.tsx
  src/components/Plugin/PluginInfoPage.tsx
  src/components/Proposal/ProposalSummary/ProposalSummary.scss
  src/components/Proposal/ProposalSummary/ProposalSummaryPluginManager.tsx
  src/lib/pluginUtils.ts
Labels: 2.0

#2180 Significant improvement for DAO name styles
  src/layouts/SidebarMenu.scss
  src/layouts/SidebarMenu.tsx
Labels: 2.0, UI

#2155 Support blockchain interaction ABI calldata
  .travis.yml
  package.json
  src/assets/locales/en/translation.json
  src/assets/styles/global-variables.scss
  src/components/Plugin/ContributionRewardExtRewarders/Competition/CreateProposal.tsx
  src/components/Proposal/Create/CreateProposal.scss
  src/components/Proposal/Create/PluginForms/ABIService.ts
  src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
  src/components/Proposal/Create/PluginForms/CreateUnknownGenericPluginProposal.tsx
  src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx
  src/components/Proposal/ProposalSummary/ProposalSummaryUnknownGenericPlugin.tsx
  src/components/Shared/Loading.scss
  src/components/Shared/SelectSearch.scss
  src/components/Shared/SelectSearch.tsx
  test/integration/proposal-genericPlugin.ts
Labels: 2.0, Feature, UI

#2184 Different message when no write methods found in ABI
  src/assets/locales/en/translation.json
  src/components/Proposal/Create/PluginForms/CreateUnknownGenericPluginProposal.tsx
Labels: 2.0

#2188 add new sidebar links - 1.0
  package-lock.json
  package.json
  src/layouts/SidebarMenu.scss
  src/layouts/SidebarMenu.tsx
  webpack.base.config.js
Labels: 1.0

#2189 add new sidebar links - 2.0
  package-lock.json
  package.json
  src/layouts/SidebarMenu.scss
  src/layouts/SidebarMenu.tsx
  webpack.base.config.js
Labels: 2.0

#2190 alchemy banner message
  src/assets/styles/global-variables.scss
  src/components/Dao/Dao.scss
  src/components/Dao/DaoContainer.tsx
  src/components/Daos/Daos.scss
  src/layouts/App.scss
  src/layouts/Header.tsx
  src/layouts/SidebarMenu.scss
Labels: 1.0

#2192 lowercase tokens, proposalState to RedemptionsTip
  data/tokens.json
  src/components/Proposal/ActionButton.tsx
Labels: 2.0, Bug

#2195 token addresses to lower case
  data/tokens.json
Labels: 1.0

#2194 add in progress label in history - 1.0
  src/components/Dao/DaoHistoryPage.scss
  src/components/Dao/DaoHistoryPage.tsx
  src/components/Proposal/ProposalHistoryRow.scss
  src/components/Proposal/ProposalHistoryRow.tsx
Labels: 1.0, UI

#2198 Unique IDs
  src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx
  test/integration/proposal-genericPlugin.ts
Labels: 2.0

#2200 Show proposal status and add proposal filtering on history page
  package.json
  src/assets/images/Icon/search.svg
  src/assets/locales/en/translation.json
  src/components/Buidlhub/Registration.scss
  src/components/Dao/Dao.scss
  src/components/Dao/DaoHistoryPage.scss
  src/components/Dao/DaoHistoryPage.tsx
  src/components/Dao/DaoPluginsPage.scss
  src/components/Proposal/ProposalHistoryRow.scss
  src/components/Proposal/ProposalHistoryRow.tsx
Labels: 2.0

#2202 Fix missing pre-boost button on a proposal card
  src/components/Proposal/ProposalCard.tsx
Labels: 2.0, Bug

#2215 Updated permissions
  src/components/Plugin/PluginContainer.tsx
  src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
Labels: 2.0

#2204 Release 1.0.0
  CHANGELOG.md
  data/tokens.json
  package-lock.json
  package.json
  src/assets/styles/global-variables.scss
  src/components/Dao/Dao.scss
  src/components/Dao/DaoContainer.tsx
  src/components/Dao/DaoHistoryPage.scss
  src/components/Dao/DaoHistoryPage.tsx
  src/components/Daos/Daos.scss
  src/components/Proposal/ProposalHistoryRow.scss
  src/components/Proposal/ProposalHistoryRow.tsx
  src/layouts/App.scss
  src/layouts/Header.tsx
  src/layouts/SidebarMenu.scss
  src/layouts/SidebarMenu.tsx
  webpack.base.config.js
Labels: 1.0

#2222 Adjustments to arc.js
  package-lock.json
  package.json
  src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
  src/components/Proposal/ProposalSummary/ProposalSummaryPluginManager.tsx
Labels: 2.0
