Repository daostack/alchemy, pull requests merged in 2020-09, with the labels that each got.

#2095 automatically refresh voting status
  CHANGELOG.md
  src/components/Proposal/ProposalDetailsPage.tsx
Labels: 1.0

#2093 Updated chrome driver for tests
  package-lock.json
  package.json
  test/integration/wdio.conf.js
Labels: 2.0

#2096 Updated Dependencies
  docker-compose.yml
  package-lock.json
  package.json
Labels: 2.0

#2102 Automatically refresh voting status
  src/components/Proposal/ProposalDetailsPage.tsx
Labels: 2.0

#2091 added default value and placeholder
  src/components/Proposal/Create/PluginForms/CreateKnownGenericPluginProposal.tsx
  src/genericPluginRegistry/plugins/NFTManager.json
Labels: 2.0

#2099 Support for Join and FundingRequest plugins (proposals are read only)
  src/assets/locales/en/translation.json
  src/components/Plugin/Plugin.scss
  src/components/Plugin/PluginContainer.tsx
  src/components/Proposal/ProposalSummary/ProposalSummary.tsx
  src/components/Proposal/ProposalSummary/ProposalSummaryFundingRequest.tsx
  src/components/Proposal/ProposalSummary/ProposalSummaryJoin.tsx
  src/lib/pluginUtils.ts
Labels: 2.0

#2127 Fix bad ui when using autocomplete input in chrome
  src/components/Daos/Daos.scss
Labels: 2.0, UI

#2123 fix misplaced against vote button
  src/components/Proposal/Voting/VoteButtons.scss
Labels: 2.0, UI

#2128 Fix vote feedback alignment
  src/components/Proposal/ProposalDetails.scss
  src/components/Proposal/Voting/VoteBreakdown.scss
Labels: 2.0, UI

#2129 Eliminate fortawesome
  package.json
  src/assets/images/Icon/social/github.svg
  src/assets/images/Icon/social/twitter.svg
  src/components/Account/Account.scss
  src/components/Account/AccountPopup.tsx
  src/components/Account/AccountProfilePage.tsx
  src/components/Dao/DaoMember.tsx
  src/index.tsx
Labels: 2.0, Maintenance

#2136 Fix wrong plugin name
  src/components/Proposal/ProposalSummary/ProposalSummaryPluginManager.tsx
Labels: 2.0

#2132 Update travis.yml to run test coverage
  .travis.yml
  package-lock.json
  package.json
Labels: 2.0

#2104 add proposal filter feature (1.0)
  package.json
  src/assets/images/Icon/search.svg
  src/components/Buidlhub/Registration.scss
  src/components/Dao/Dao.scss
  src/components/Dao/DaoHistoryPage.scss
  src/components/Dao/DaoHistoryPage.tsx
  src/components/Shared/ProposalDescription.tsx
Labels: 1.0

#2138 don't show email button on xDAI
  src/components/Daos/DaosPage.tsx
Labels: 1.0, UI

#2137 remove vote/staking status message on executed proposals
  src/components/Proposal/Staking/StakeButtons.tsx
  src/components/Proposal/Voting/VoteButtons.tsx
Labels: 1.0, Bug, UI

#2141 Fix no side bar modal scrolling
  src/components/Proposal/Create/CreateProposal.scss
Labels: 2.0

#2139 show holdings when no DAO
  src/components/Account/AccountBalances.tsx
  src/components/Account/AccountProfilePage.tsx
  src/layouts/App.scss
  test/integration/profile.ts
Labels: 1.0, Feature, UI

#2140 Update arc.js 56 ; use polling
  package-lock.json
  package.json
  src/components/Account/AccountBalances.tsx
  src/components/Account/AccountProfilePage.tsx
  src/components/Dao/DaoContainer.tsx
  src/components/Dao/DaoHistoryPage.tsx
  src/components/Dao/DaoPluginsPage.tsx
  src/components/Dao/ProposalPluginCard.tsx
  src/components/Daos/DaosPage.tsx
  src/components/Plugin/ContributionRewardExtRewarders/Competition/Details.tsx
  src/components/Plugin/ContributionRewardExtRewarders/Competition/List.tsx
  src/components/Plugin/ContributionRewardExtRewarders/Competition/utils.ts
  src/components/Plugin/ContributionRewardExtRewarders/DetailsPageRouter.tsx
  src/components/Plugin/PluginContainer.tsx
  src/components/Plugin/PluginProposalsPage.tsx
  src/components/Proposal/ActionButton.tsx
  src/components/Proposal/ProposalCard.tsx
  src/components/Proposal/ProposalData.tsx
  src/components/Proposal/ProposalDetailsPage.tsx
  src/components/Proposal/RedemptionsString.tsx
  src/components/Proposal/RedemptionsTip.tsx
  src/components/Redemptions/RedemptionsButton.tsx
  src/components/Redemptions/RedemptionsMenu.tsx
  src/components/Redemptions/RedemptionsPage.tsx
  src/components/Shared/PreTransactionModal.tsx
  src/layouts/Header.tsx
  src/layouts/SidebarMenu.tsx
  src/settings.ts
Labels: 2.0

#2144 Support Join and FundingRequest creation in PluginManager
  src/components/Proposal/Create/PluginForms/CreatePluginManagerProposal.tsx
  src/components/Proposal/Create/PluginForms/PluginInitializeFields.tsx
Labels: 2.0

#2149 Fix Enable Prediction button text overflows
  src/components/Proposal/Staking/StakeButtons.scss
Labels: 2.0, UI
