Repository daostack/alchemy, pull requests merged in 2021-02, with the labels that each got.

#2412 A minor fix to show the proper end time of a CL4R scheme
  src/components/Scheme/CL4R/CL4RHelper.tsx
Labels: Bug

#2408 Better approach to calculate a proposal status
  CHANGELOG.md
  src/lib/proposalHelpers.ts
  src/subgraph_endpoints.json
Labels: Bug, UI

#2413 mcgs - hard coded proxy contracts support - workaround.
  src/components/Proposal/Create/SchemeForms/ABIService.ts
Labels: Bug

#2415 A robust way to handle small REP amounts and times in CL4R scheme
  package-lock.json
  package.json
  src/components/Scheme/CL4R/CL4R.tsx
  src/components/Scheme/CL4R/CL4RHelper.tsx
  src/components/Scheme/CL4R/LockRow.tsx
  src/components/Scheme/CL4R/PeriodRow.tsx
  src/lib/util.ts
Labels: Improvement

#2403 Release 1.0.6
  CHANGELOG.md
  README.md
  data/tokens.json
  package-lock.json
  package.json
  src/@store/arc/arcActions.ts
  src/components/Account/AccountProfileName.tsx
  src/components/Notification/Notification.scss
  src/components/Proposal/Create/SchemeForms/ABIService.ts
  src/components/Proposal/Create/SelectProposal/SelectProposal.tsx
  src/components/Proposal/ProposalCard.scss
  src/components/Proposal/Voting/VotersModal.scss
  src/components/Proposal/Voting/VotersModal.tsx
  src/components/Scheme/CL4R/CL4R.scss
  src/components/Scheme/CL4R/CL4R.tsx
  src/components/Scheme/CL4R/CL4RHelper.tsx
  src/components/Scheme/CL4R/LockRow.scss
  src/components/Scheme/CL4R/LockRow.tsx
  src/components/Scheme/CL4R/PeriodRow.scss
  src/components/Scheme/CL4R/PeriodRow.tsx
  src/components/Scheme/Scheme.scss
  src/components/Scheme/SchemeContainer.tsx
  src/components/Scheme/SchemeInfoPage.tsx
  src/lib/proposalHelpers.ts
  src/lib/schemeUtils.ts
  src/lib/util.ts
  src/subgraph_endpoints.json
  tsconfig.json
Labels: Release

#2417 Add CopyToClipboard option near the selected contract
  src/components/Proposal/Create/SchemeForms/CreateGenericMultiCallProposal.tsx
Labels: Improvement, UX

#2419 Vertical scrolling is added to the sidebar
  src/layouts/SidebarMenu.scss
Labels: UI

#2422 Clean up Alchemy's top bar
  package-lock.json
  package.json
  src/@store/ui/uiActions.ts
  src/@store/ui/uiReducer.ts
  src/assets/images/Icon/menu/redemption.svg
  src/components/Dao/DaoMembersPage.tsx
  src/components/Dao/DaoProposalsPage.tsx
  src/components/Dao/DaoSchemesPage.tsx
  src/components/Dao/ProposalSchemeCard.tsx
  src/components/Proposal/ActionButton.scss
  src/components/Proposal/Create/CreateProposalPage.tsx
  src/components/Proposal/Create/SchemeForms/CreateContributionRewardProposal.tsx
  src/components/Proposal/Create/SchemeForms/CreateGenericMultiCallProposal.tsx
  src/components/Proposal/Create/SchemeForms/CreateKnownGenericSchemeProposal.tsx
  src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx
  src/components/Proposal/Create/SchemeForms/CreateUnknownGenericSchemeProposal.tsx
  src/components/Proposal/ProposalCard.tsx
  src/components/Proposal/ProposalDetailsPage.tsx
  src/components/Redemptions/RedemptionsButton.scss
  src/components/Redemptions/RedemptionsButton.tsx
  src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateProposal.tsx
  src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateSubmission.tsx
  src/components/Scheme/ContributionRewardExtRewarders/Competition/Details.tsx
  src/components/Scheme/ContributionRewardExtRewarders/Competition/List.tsx
  src/components/Scheme/ReputationFromToken.tsx
  src/components/Scheme/SchemeContainer.tsx
  src/components/Scheme/SchemeInfoPage.tsx
  src/components/Scheme/SchemeOpenBountyPage.tsx
  src/components/Scheme/SchemeProposalsPage.tsx
  src/components/Shared/TrainingTooltip.scss
  src/components/Shared/TrainingTooltip.tsx
  src/layouts/App.scss
  src/layouts/Header.tsx
  src/layouts/SidebarMenu.tsx
  src/settings.ts
  test/integration/utils.ts
Labels: Improvement, UI

#2421 Update changelog for v1.0.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog
