Repository daostack/alchemy, pull requests merged in 2021-01, with the labels that each got.

#2384 Whitelist Prime DAO token - fix
  data/tokens.json
Labels: Bug

#2387 Bump version and updated changelog to release 1.0.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog

#2391 Fix enable predictions button text overflows
  src/components/Proposal/Staking/StakeButtons.scss
Labels: UI

#2393 Better UI for multicall summary with long parameters list method
  src/components/Proposal/ProposalDetails.scss
  src/components/Proposal/ProposalSummary/ProposalSummaryMultiCallGenericScheme.tsx
Labels: UI

#2392 Updated daocreator v.22
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/DaoCreator/index.tsx
Labels: Bug

#2395 fixes #2394
  src/components/Proposal/Create/SchemeForms/Validators.ts
Labels: Bug

#2381 Support CL4R
  package-lock.json
  package.json
  src/@store/arc/arcActions.ts
  src/components/Account/AccountProfileName.tsx
  src/components/Notification/Notification.scss
  src/components/Proposal/Create/SelectProposal/SelectProposal.tsx
  src/components/Proposal/Voting/VotersModal.scss
  src/components/Proposal/Voting/VotersModal.tsx
  src/components/Scheme/CL4R/CL4R.scss
  src/components/Scheme/CL4R/CL4R.tsx
  src/components/Scheme/CL4R/CL4RHelper.tsx
  src/components/Scheme/CL4R/LockRow.scss
  src/components/Scheme/CL4R/LockRow.tsx
  src/components/Scheme/CL4R/PeriodRow.scss
  src/components/Scheme/CL4R/PeriodRow.tsx
  src/components/Scheme/Scheme.scss
  src/components/Scheme/SchemeContainer.tsx
  src/components/Scheme/SchemeInfoPage.tsx
  src/lib/schemeUtils.ts
  src/lib/util.ts
  src/subgraph_endpoints.json
  tsconfig.json
Labels: Feature

#2399 Better UI for action buttons
  src/components/Proposal/ProposalCard.scss
Labels: UI

#2398 Update changelog for 1.0.6 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog

#2405 Show GP address in scheme info page
  src/components/Scheme/SchemeInfoPage.tsx
Labels: Bug

#2404 Use subgraph v48 ; update changelog ; show GP address in multicall info page
  CHANGELOG.md
  src/components/Scheme/SchemeInfoPage.tsx
  src/subgraph_endpoints.json
Labels: Bug, changelog
